name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Lucaszzv
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
- name: Generate Datas
  run: |
    git config --global user.name "Lucaszzv"
    git config --global user.email "pokedigedg@gmail.com"
    git remote set-url origin https://seu-username:${{ secrets.ACTIONS_TOKEN }}@github.com/usuario-repo/repo.git
- name: Commit e push mudanças
  run: |
    git config user.name "GitHub Actions"
    git config user.email "actions@github.com"
    git add .
    git commit -m "Commit automatizado por GitHub Actions"
    git push origin HEAD:${{ github.ref }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
